### ISSUE TITLE
Python2 support and EOL

### ISSUE THREAD

**Issue by edouard-lopez** [lovato/hooks4git#49]
I saw you have [code to support Python `2.7`](https://github.com/lovato/hooks4git/blob/develop/hooks4git/scripts.py#L35). This version will [not be maintained past january 2020](https://pythonclock.org/).

If you want to support it anyway, yet simplify your code, you could use [`future` module](https://pypi.org/project/future/). Then for above code simply do:

     from builtins import input

**Comment by lovato** [comment]
Well, at first, I was willing to make hooks4git a python dependency, then once you clone a project an install everything, it would auto hook your folder. But this happens only the first time when the package is still in egg format. Then it is converted (and cached) to wheel, which doesn't execute code upon installation.

So I would be willing to remove all this user wizard input, since making it behave like a tool created a simpler workflow. 

Like, it is simpler not being able to do something and ask for a --force parameter, than handle a dialog with the user.

**Comment by edouard-lopez** [comment]
Ok, didn't realize you are not using this method. So could be delete

Using flags is indeed a better solution IMHO.

**Comment by lovato** [comment]
Well, it is already deleted on develop. I did some work adding a few more tests, and a cleanup. Right now hooks4git is using 'itself' inside CI on develop. I have a few more details to catch on develop, and then I will release another version.
Then, start working on a major rework allowing code to be tested.
